.\" $Id: anydim.1,v 1.5 2011-01-04 23:04:55 grahn Exp $
.\" $Name:  $
.
.
.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.
.TH anydim 1 "JAN 2011" "Anydim" "User Manuals"
.
.SH "NAME"
anydim \- print width and height of images
.
.SH "SYNOPSIS"
.B anydim
.I file
\&...
.br
.B anydim
.B --version
.br
.B anydim
.B --help
.
.SH "DESCRIPTION"
.B anydim
simply prints the width and height of the image files given
as command-line arguments.
.SS "Supported file formats"
.IP JPEG
Plain JFIF or EXIF; progressive JPEG.
.
.SH "OPTIONS"
None.
.
.SH "EXIT CODE"
Non-zero if at least one image failed to yield its dimensions.
.
.SH "BUGS"
Only
.B JPEG
images are supported so far, despite the
.B any
in its name.
.
.SH "AUTHOR"
J\(:orgen Grahn
.IR \[fo]grahn+src@snipabacken.se\[fc] .
Licensed under the Modified BSD license.
.
.SH "SEE ALSO"
.BR jpeginfo (1).
